principle = int(input("enter principle: "))
rate = int(input("enter rate: "))
time = int(input("enter rate: "))
n = int(input("enter n: "))
compound_interst = principle*(1+(rate/100))**(n*time)
print(compound_interst)